export function Answer({
  participantId,
  sessionId,
  studyId,
  treatmentId,
  position,
  viewType,
  interaction,
  variableAmount,
  amountEarlier,
  timeEarlier,
  dateEarlier,
  amountLater,
  timeLater,
  dateLater,
  maxAmount,
  maxTime,
  verticalPixels,
  horizontalPixels,
  leftMarginWidthIn,
  bottomMarginHeightIn,
  graphWidthIn,
  graphHeightIn,
  widthIn,
  heightIn,
  showMinorTicks,
  choice,
  dragAmount,
  shownTimestamp,
  choiceTimestamp,
  choiceTimeSec,
}) {
  return {
    participantId: participantId,
    sessionId: sessionId,
    studyId: studyId,
    treatmentId: treatmentId,
    position: position,
    viewType: viewType,
    interaction: interaction,
    variableAmount: variableAmount,
    amountEarlier: amountEarlier,
    timeEarlier: timeEarlier,
    dateEarlier: dateEarlier,
    amountLater: amountLater,
    timeLater: timeLater,
    dateLater: dateLater,
    maxAmount: maxAmount,
    maxTime: maxTime,
    verticalPixels: verticalPixels,
    horizontalPixels: horizontalPixels,
    leftMarginWidthIn: leftMarginWidthIn,
    bottomMarginHeightIn: bottomMarginHeightIn,
    graphWidthIn: graphWidthIn,
    graphHeightIn: graphHeightIn,
    widthIn: widthIn,
    heightIn: heightIn,
    showMinorTicks: showMinorTicks,
    choice: choice,
    dragAmount: dragAmount,
    shownTimestamp: shownTimestamp,
    choiceTimestamp: choiceTimestamp,
    choiceTimeSec: choiceTimeSec,
  };
}
