export function Question({
  treatmentId,
  position,
  viewType,
  interaction,
  variableAmount,
  amountEarlier,
  timeEarlier,
  dateEarlier,
  amountLater,
  timeLater,
  dateLater,
  maxAmount,
  maxTime,
  horizontalPixels,
  verticalPixels,
  leftMarginWidthIn,
  bottomMarginHeightIn,
  graphWidthIn,
  graphHeightIn,
  widthIn,
  heightIn,
  showMinorTicks,
  comment,
  instructionGifPrefix,
}) {
  return {
    treatmentId: treatmentId,
    position: position,
    viewType: viewType,
    interaction: interaction,
    variableAmount: variableAmount,
    amountEarlier: amountEarlier,
    timeEarlier: timeEarlier,
    dateEarlier: dateEarlier,
    amountLater: amountLater,
    timeLater: timeLater,
    dateLater: dateLater,
    maxAmount: maxAmount,
    maxTime: maxTime,
    horizontalPixels: horizontalPixels,
    verticalPixels: verticalPixels,
    leftMarginWidthIn: leftMarginWidthIn,
    bottomMarginHeightIn: bottomMarginHeightIn,
    graphWidthIn: graphWidthIn,
    graphHeightIn: graphHeightIn,
    widthIn: widthIn,
    heightIn: heightIn,
    showMinorTicks: showMinorTicks,
    comment: comment,
    instructionGifPrefix: instructionGifPrefix,
    highup: null,
    lowdown: null,
  };
}
