export const Question = ({
  questionId,
  derivedFromQuestionId,
  amountEarlier,
  timeEarlier,
  dateEarlier,
  amountLater,
  timeLater,
  dateLater,
  maxAmount,
  maxTime,
  questionComment,
}) =>
  Object.freeze({
    questionId,
    derivedFromQuestionId,
    amountEarlier,
    timeEarlier,
    dateEarlier,
    amountLater,
    timeLater,
    dateLater,
    maxAmount,
    maxTime,
    questionComment,
  });
