export const ScreenAttributes = ({
  availHeight,
  availWidth,
  availLeft,
  availTop,
  colorDepth,
  width,
  height,
  orientationAngle,
  orientationType,
  pixelDepth,
  isExtended,
}) =>
  Object.freeze({
    availHeight,
    availWidth,
    availLeft,
    availTop,
    colorDepth,
    width,
    height,
    orientationAngle,
    orientationType,
    pixelDepth,
    isExtended,
  });
